version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  nginx:
    image: nginx:1.24-alpine
    ports:
      - 3000:80
    volumes:
      - ./.docker/conf/nginx/taxi-park.conf:/etc/nginx/conf.d/taxi-park.conf
    depends_on:
      - database

###< doctrine/doctrine-bundle ###
