version: "3"

services:

  database:
    container_name: postgres
    image: postgres:15
    volumes:
      - db_app:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    networks:
      - symfony_app

  database_test:
    container_name: postgres_test
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db_app:/var/lib/postgresql/data:rw
    ports:
      - "5433:5432"
    networks:
      - symfony_app

  php:
    build:
      context: ./.docker/php
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ../:/var/www/symfony:cached
      - symfony_app_var:/var/www/symfony/var
      - symfony_app_vendor:/var/www/symfony/vendor
    networks:
      - symfony_app

  nginx:
    build:
      context: ./.docker/nginx
    volumes:
      - ../:/var/www/symfony:cached
      - symfony_app_var:/var/www/symfony/var
      - symfony_app_vendor:/var/www/symfony/vendor
    ports:
      - 8080:80
    networks:
      - symfony_app
    env_file:
      - .docker/.env.nginx

volumes:
  symfony_app_var:
  symfony_app_vendor:
  db_app:

networks:
  symfony_app:
